### ISSUE TITLE
Suggestion: OpenAPI definition

### ISSUE THREAD

**Issue by petrkr** [AlzaBox/AlzaBox-API-SDK-csharp#5]
If you will do OpenAPI definition, then you can use swagger to auto-generate model for other languages too (python, typescript....) and also by using swagger you can have also Mock server with easy web-based API calls. Really useful for debugging.

Now you are aimed only for C# clients and rest have to read it from this code and rewrite.

But it is just suggestion how to NOT do same work many times (for many languages).

**Comment by ABMaMa** [comment]
since the last sprint we have been converting our code from the apiblueprint (apiary) to the openapi definition. it will be done soon.

**Comment by ABMaMa** [comment]
https://github.com/AlzaBox/AlzaBox-API-Description

**Comment by ABMaMa** [comment]
https://github.com/AlzaBox/AlzaBox-API-Description
